// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

// To overcome the version conflict between NUnit's version this internal classes have been introduced

namespace NUnit.Framework
{
    internal class TestFixtureSetUpAttribute : SetUpAttribute
    {
    }

    internal class TestFixtureTearDownAttribute : TearDownAttribute
    {
    }
}